services:
  django:
    build:
      context: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/file_management_service
    ports:
      - "8000:8000"
    environment:
      - GRPC_HOST=grpc
    depends_on:
      db:
        condition: service_healthy

  grpc:
    build:
      context: ./grpc
    command: python grpc_server.py
    volumes:
      - ./grpc:/file_management_system
    ports:
      - "50051:50051"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=file-management-service
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d/
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=file-management-service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
