# Use the official Node.js image as a base
FROM node:20.15.0
ARG VITE_REACT_PORT
ENV VITE_REACT_PORT=$VITE_REACT_PORT
# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install 

# Copy the rest of the application code
COPY . .

# Expose the port Vite runs on
EXPOSE ${VITE_REACT_PORT}

# Start the application
CMD ["npm", "run", "dev"]
