# Use a node base image to build the React app
FROM node:20.15.0 AS build
ARG VITE_REACT_PORT
ENV VITE_REACT_PORT=$VITE_REACT_PORT
# Set working directory
WORKDIR /app
# Install dependencies
COPY package.json ./
RUN npm install

# Copy source files
COPY . .

# Build the React app
RUN npm run build

# Use an nginx base image to serve the built React app
FROM nginx:alpine

# Copy the build files to the nginx directory
COPY --from=build /app/build /usr/share/nginx/html
# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf
# Expose port 80
EXPOSE 81

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
