# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_code/fileManagementService.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%grpc_code/fileManagementService.proto\x12\x0bgrpc_server\".\n\x08userFile\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x10\n\x08\x66ilePath\x18\x02 \x01(\t\"@\n\x08\x66ullFile\x12\x10\n\x08userName\x18\x01 \x01(\t\x12\x10\n\x08\x66ileName\x18\x02 \x01(\t\x12\x10\n\x08\x66ilePath\x18\x03 \x01(\t\"K\n\x13UploadRecordRequest\x12\x10\n\x08userName\x18\x01 \x01(\t\x12\x10\n\x08\x66ileName\x18\x02 \x01(\t\x12\x10\n\x08\x66ilePath\x18\x03 \x01(\t\"J\n\x0eUploadResponse\x12\'\n\x06status\x18\x01 \x01(\x0e\x32\x17.grpc_server.statusType\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\x11GetRecordsRequest\x12\x10\n\x08userName\x18\x01 \x01(\t\"9\n\x11GetRecordResponse\x12$\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x15.grpc_server.userFile\"N\n\x16GetPtclrRecordsRequest\x12\x10\n\x08userName\x18\x01 \x01(\t\x12\x10\n\x08\x66ileName\x18\x02 \x01(\t\x12\x10\n\x08\x66ilePath\x18\x03 \x01(\t\"?\n\x17GetPtclrRecordsResponse\x12$\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x15.grpc_server.fullFile\"I\n\x11\x44\x65lRecordsRequest\x12\x10\n\x08userName\x18\x01 \x01(\t\x12\x10\n\x08\x66ileName\x18\x02 \x01(\t\x12\x10\n\x08\x66ilePath\x18\x03 \x01(\t\"N\n\x12\x44\x65lRecordsResponse\x12\'\n\x06status\x18\x01 \x01(\x0e\x32\x17.grpc_server.statusType\x12\x0f\n\x07message\x18\x02 \x01(\t*0\n\nstatusType\x12\x0b\n\x07unknown\x10\x00\x12\x0b\n\x07success\x10\x01\x12\x08\n\x04\x66\x61il\x10\x02\x32\xf0\x02\n\x15\x46ileManagementService\x12N\n\nGetRecords\x12\x1e.grpc_server.GetRecordsRequest\x1a\x1e.grpc_server.GetRecordResponse\"\x00\x12O\n\x0cUploadRecord\x12 .grpc_server.UploadRecordRequest\x1a\x1b.grpc_server.UploadResponse\"\x00\x12\x63\n\x14GetParticularRecords\x12#.grpc_server.GetPtclrRecordsRequest\x1a$.grpc_server.GetPtclrRecordsResponse\"\x00\x12Q\n\x0c\x44\x65leteRecord\x12\x1e.grpc_server.DelRecordsRequest\x1a\x1f.grpc_server.DelRecordsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_code.fileManagementService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSTYPE']._serialized_start=719
  _globals['_STATUSTYPE']._serialized_end=767
  _globals['_USERFILE']._serialized_start=54
  _globals['_USERFILE']._serialized_end=100
  _globals['_FULLFILE']._serialized_start=102
  _globals['_FULLFILE']._serialized_end=166
  _globals['_UPLOADRECORDREQUEST']._serialized_start=168
  _globals['_UPLOADRECORDREQUEST']._serialized_end=243
  _globals['_UPLOADRESPONSE']._serialized_start=245
  _globals['_UPLOADRESPONSE']._serialized_end=319
  _globals['_GETRECORDSREQUEST']._serialized_start=321
  _globals['_GETRECORDSREQUEST']._serialized_end=358
  _globals['_GETRECORDRESPONSE']._serialized_start=360
  _globals['_GETRECORDRESPONSE']._serialized_end=417
  _globals['_GETPTCLRRECORDSREQUEST']._serialized_start=419
  _globals['_GETPTCLRRECORDSREQUEST']._serialized_end=497
  _globals['_GETPTCLRRECORDSRESPONSE']._serialized_start=499
  _globals['_GETPTCLRRECORDSRESPONSE']._serialized_end=562
  _globals['_DELRECORDSREQUEST']._serialized_start=564
  _globals['_DELRECORDSREQUEST']._serialized_end=637
  _globals['_DELRECORDSRESPONSE']._serialized_start=639
  _globals['_DELRECORDSRESPONSE']._serialized_end=717
  _globals['_FILEMANAGEMENTSERVICE']._serialized_start=770
  _globals['_FILEMANAGEMENTSERVICE']._serialized_end=1138
# @@protoc_insertion_point(module_scope)
